// Bot matnlari (O'zbekcha / Ruscha). t(lang, kalit, {param}) orqali olinadi.
const S = {
  uz: {
    btn_report_kassa: '💵 Kassa farqi (Fakt va Poster)',
    btn_lang: '🌐 Til: O\'zbekcha',
    btn_back: '◀️ Orqaga',
    btn_menu: '🏠 Bosh menyu',
    btn_all: '✅ Hammasi',
    btn_clear: '🧹 Tozalash',
    btn_make: '📄 PDF yaratish',
    btn_cancel: '✖️ Bekor qilish',
    p_yesterday: 'Kecha',
    p_today: 'Bugun',
    p_last7: 'Oxirgi 7 kun',
    p_month: 'Shu oy',
    p_prevmonth: 'O\'tgan oy',
    p_custom: '📅 Sanani yozish',
    menu_title: '🏠 *Mondo Bot*\nKerakli bo\'limni tanlang:',
    menu_empty: 'Sizga hozircha hisobot bo\'limlari ochilmagan. Administratorga murojaat qiling.',
    pick_period: '📅 *{report}*\nDavrni tanlang:',
    pick_spots: '🏪 *{report}*\nDavr: {period}\n\nFiliallarni belgilang (bir nechta tanlash mumkin), keyin «PDF yaratish» tugmasini bosing.\nTanlangan: {n} ta',
    ask_dates: '📅 Sanani yozing:\n• bitta kun: `07.10.2026`\n• davr: `01.10.2026 - 07.10.2026`',
    bad_dates: '⚠️ Sana tushunarsiz. Masalan: `07.10.2026` yoki `01.10.2026 - 07.10.2026`.',
    dates_future: '⚠️ Kelajak sanasini tanlab bo\'lmaydi.',
    dates_long: '⚠️ Davr 92 kundan oshmasligi kerak.',
    no_spots_chosen: '⚠️ Avval kamida bitta filial tanlang.',
    generating: '⏳ PDF tayyorlanmoqda...',
    done: '✅ Tayyor.',
    gen_error: '⚠️ PDF yaratishda xato: {msg}',
    busy: '⏳ Oldingi hisobot hali tayyorlanmoqda, biroz kuting.',
    expired: 'Bu tugma eskirgan. Bosh menyudan qayta boshlang.',
    lang_set: 'Til o\'zgartirildi: O\'zbekcha 🇺🇿',
    start_linked: '✅ Salom, {login}! Hisobingiz Telegram bilan bog\'landi.\nSaytdagi kabi huquqlaringiz botda ham amal qiladi.',
    not_registered: '🔒 Siz hali ro\'yxatda yo\'qsiz.\n\nAdministratorga Telegram username\'ingizni ayting: {username}\nU saytdagi profilingizga yozgach, qaytadan /start yuboring.',
    no_username: '🔒 Telegram profilingizda username yo\'q.\nTelegram → Sozlamalar → Username bo\'limida username qo\'ying, keyin administratorga ayting va /start yuboring.',
    taken: '⚠️ Bu hisob boshqa Telegram profiliga bog\'langan. Administratorga murojaat qiling.',
    inactive: '🔒 Hisobingiz faolsizlantirilgan. Administratorga murojaat qiling.',
    unlinked: '🔒 Sizning hisobingiz bog\'lanmagan. /start yuboring.',
    no_access: '🔒 Bu hisobotga ruxsatingiz yo\'q.',
    no_spots_access: '🔒 Sizga filiallar biriktirilmagan.',
    private_only: 'Bot bilan shaxsiy chatda ishlang.',
    group_admin_only: '🔒 Guruhni faqat Telegram\'i bog\'langan admin ulashi mumkin.',
    group_ok: '✅ Guruh ulandi{title}. Endi admin panelda «Avto-hisobotlar» bo\'limida bu guruhni tanlang.',
    // PDF
    k_title: 'Kassa farqi — Fakt va Poster',
    k_period: 'Davr: {period}',
    k_spots: 'Filiallar: {n} ta',
    k_made: 'Tuzildi: {time}',
    k_col_spot: 'Filial',
    k_col_fakt: 'Fakt, so\'m',
    k_col_poster: 'Poster, so\'m',
    k_col_diff: 'Farq, so\'m',
    k_col_pct: 'Farq, %',
    k_col_status: 'Holat / Izoh',
    k_total: 'JAMI',
    k_ok: 'To\'g\'ri',
    k_not_posted: '{x} so\'m Posterga urilmagan',
    k_less: 'Kassa {x} so\'m kam topshirilgan',
    k_over: 'chegaradan oshgan',
    k_over_n: '{n} kun chegaradan oshgan',
    k_no_entry: 'Kassa kiritilmagan',
    k_missing_n: '{n} kun kiritilmagan',
    k_waiting: 'Hisoblanmagan (kutilmoqda)',
    k_waiting_n: '{n} kun hisoblanmagan',
    k_note: 'Farq = Poster − Fakt. Qizil «-»: Fakt Posterdan ko\'p (Posterga urilmagan). Sariq: Fakt Posterdan kam (kassa kam topshirilgan). Yashil: mos (1 000 so\'mgacha). Chegara: {limit}%.',
    d_yesterday: 'kecha',
    d_today: 'bugun',
    file_kassa: 'kassa-farqi',
    // KPI / Bonus holati
    btn_report_kpi: '🎯 KPI / Bonus holati',
    btn_report_sales: '🍦 Kunlik savdo (kategoriya bo\'yicha)',
    p_title: 'KPI / Bonus holati',
    p_col_calc: 'Hisoblangan, so\'m',
    p_col_given: 'Berildi, so\'m',
    p_col_held: 'Berilmadi, so\'m',
    p_col_pending: 'Kutilmoqda, so\'m',
    p_all_given: 'Hammasi berildi',
    p_held_1: 'Berilmadi (kassa farqi chegaradan oshgan)',
    p_held_n: '{n} kun berilmadi (kassa farqi chegaradan oshgan)',
    p_noentry_1: 'Kassa kiritilmagan',
    p_noentry_n: '{n} kunda kassa kiritilmagan',
    p_wait_1: 'Poster bilan tekshiruv kutilmoqda',
    p_wait_n: '{n} kun tekshiruv kutilmoqda',
    p_nodata: 'Bonus hisoblanmagan',
    p_note: 'Hisoblangan — kategoriyalar bo\'yicha bonus yig\'indisi. Berildi: kassa Poster bilan solishtirilgan va farq chegarada ({limit}%). Berilmadi: kassa farqi chegaradan oshgan. Kutilmoqda: kassa kiritilmagan yoki hali tekshirilmagan.',
    file_kpi: 'kpi-bonus',
    // Kunlik savdo
    s_title: 'Kunlik savdo — kategoriya bo\'yicha',
    s_col_cat: 'Kategoriya',
    s_cats: 'Kategoriyalar: {n} ta',
    s_cats_all: 'Kategoriyalar: {n} ta (hammasi)',
    s_note: 'Birlik nomdan keyin ko\'rsatilgan (dona — dona, kg — kilogramm).',
    s_note_flip: 'Kategoriyalar soni 8 tadan ko\'p bo\'lgani uchun kategoriyalar qatorga, filiallar ustunga o\'tkazildi — hamma narsa bitta listga sig\'adi.',
    u_dona: 'dona',
    u_kg: 'kg',
    file_sales: 'kunlik-savdo',
    btn_cats: '🗂 Kategoriyalar: {n}/{m}',
    pick_cats: '🗂 *{report}*\nKategoriyalarni belgilang:\nTanlangan: {n}/{m}',
    no_cats_chosen: '⚠️ Kamida bitta kategoriya tanlang.',
    btn_back_spots: '◀️ Filiallarga qaytish',
  },
  ru: {
    btn_report_kassa: '💵 Разница кассы (Факт и Poster)',
    btn_lang: '🌐 Язык: Русский',
    btn_back: '◀️ Назад',
    btn_menu: '🏠 Главное меню',
    btn_all: '✅ Все',
    btn_clear: '🧹 Сбросить',
    btn_make: '📄 Создать PDF',
    btn_cancel: '✖️ Отмена',
    p_yesterday: 'Вчера',
    p_today: 'Сегодня',
    p_last7: 'Последние 7 дней',
    p_month: 'Этот месяц',
    p_prevmonth: 'Прошлый месяц',
    p_custom: '📅 Ввести дату',
    menu_title: '🏠 *Mondo Bot*\nВыберите раздел:',
    menu_empty: 'Вам пока не открыты разделы отчётов. Обратитесь к администратору.',
    pick_period: '📅 *{report}*\nВыберите период:',
    pick_spots: '🏪 *{report}*\nПериод: {period}\n\nОтметьте филиалы (можно несколько), затем нажмите «Создать PDF».\nВыбрано: {n}',
    ask_dates: '📅 Введите дату:\n• один день: `07.10.2026`\n• период: `01.10.2026 - 07.10.2026`',
    bad_dates: '⚠️ Дата не распознана. Например: `07.10.2026` или `01.10.2026 - 07.10.2026`.',
    dates_future: '⚠️ Нельзя выбрать будущую дату.',
    dates_long: '⚠️ Период не должен превышать 92 дня.',
    no_spots_chosen: '⚠️ Сначала выберите хотя бы один филиал.',
    generating: '⏳ PDF готовится...',
    done: '✅ Готово.',
    gen_error: '⚠️ Ошибка при создании PDF: {msg}',
    busy: '⏳ Предыдущий отчёт ещё готовится, подождите.',
    expired: 'Эта кнопка устарела. Начните заново из главного меню.',
    lang_set: 'Язык изменён: Русский 🇷🇺',
    start_linked: '✅ Здравствуйте, {login}! Ваш аккаунт привязан к Telegram.\nПрава доступа такие же, как на сайте.',
    not_registered: '🔒 Вы пока не в списке.\n\nСообщите администратору ваш Telegram username: {username}\nКогда он впишет его в ваш профиль на сайте, снова отправьте /start.',
    no_username: '🔒 В вашем профиле Telegram нет username.\nУстановите его: Telegram → Настройки → Имя пользователя, затем сообщите администратору и отправьте /start.',
    taken: '⚠️ Этот аккаунт привязан к другому профилю Telegram. Обратитесь к администратору.',
    inactive: '🔒 Ваш аккаунт отключён. Обратитесь к администратору.',
    unlinked: '🔒 Ваш аккаунт не привязан. Отправьте /start.',
    no_access: '🔒 У вас нет доступа к этому отчёту.',
    no_spots_access: '🔒 Вам не назначены филиалы.',
    private_only: 'Работайте с ботом в личном чате.',
    group_admin_only: '🔒 Подключить группу может только администратор с привязанным Telegram.',
    group_ok: '✅ Группа подключена{title}. Теперь выберите её в админ-панели, раздел «Авто-отчёты».',
    k_title: 'Разница кассы — Факт и Poster',
    k_period: 'Период: {period}',
    k_spots: 'Филиалов: {n}',
    k_made: 'Создано: {time}',
    k_col_spot: 'Филиал',
    k_col_fakt: 'Факт, сум',
    k_col_poster: 'Poster, сум',
    k_col_diff: 'Разница, сум',
    k_col_pct: 'Разн., %',
    k_col_status: 'Статус / Комментарий',
    k_total: 'ИТОГО',
    k_ok: 'Верно',
    k_not_posted: '{x} сум не пробито в Poster',
    k_less: 'Касса сдана на {x} сум меньше',
    k_over: 'превышает лимит',
    k_over_n: 'лимит превышен: {n} дн.',
    k_no_entry: 'Касса не внесена',
    k_missing_n: 'не внесено: {n} дн.',
    k_waiting: 'Не рассчитано (ожидание)',
    k_waiting_n: 'не рассчитано: {n} дн.',
    k_note: 'Разница = Poster − Факт. Красный «-»: Факт больше Poster (не пробито в Poster). Жёлтый: Факт меньше Poster (касса сдана меньше). Зелёный: совпадает (до 1 000 сум). Лимит: {limit}%.',
    d_yesterday: 'вчера',
    d_today: 'сегодня',
    file_kassa: 'raznitsa-kassy',
    // KPI / Bonus holati
    btn_report_kpi: '🎯 KPI / Статус бонуса',
    btn_report_sales: '🍦 Дневные продажи (по категориям)',
    p_title: 'KPI / Статус бонуса',
    p_col_calc: 'Начислено, сум',
    p_col_given: 'Выдано, сум',
    p_col_held: 'Не выдано, сум',
    p_col_pending: 'Ожидает, сум',
    p_all_given: 'Выдан полностью',
    p_held_1: 'Не выдан (разница кассы превышает лимит)',
    p_held_n: 'Не выдан: {n} дн. (разница кассы превышает лимит)',
    p_noentry_1: 'Касса не внесена',
    p_noentry_n: 'Касса не внесена: {n} дн.',
    p_wait_1: 'Ожидается сверка с Poster',
    p_wait_n: 'Ожидается сверка: {n} дн.',
    p_nodata: 'Бонус не начислялся',
    p_note: 'Начислено — сумма бонусов по категориям. Выдано: касса сверена с Poster и разница в пределах лимита ({limit}%). Не выдано: разница кассы превышает лимит. Ожидает: касса не внесена или ещё не сверена.',
    file_kpi: 'kpi-bonus',
    s_title: 'Дневные продажи — по категориям',
    s_col_cat: 'Категория',
    s_cats: 'Категорий: {n}',
    s_cats_all: 'Категорий: {n} (все)',
    s_note: 'Единица измерения указана после названия (шт — штуки, кг — килограммы).',
    s_note_flip: 'Категорий больше 8, поэтому категории выведены в строки, а филиалы — в столбцы: всё помещается на одном листе.',
    u_dona: 'шт',
    u_kg: 'кг',
    file_sales: 'dnevnye-prodazhi',
    btn_cats: '🗂 Категории: {n}/{m}',
    pick_cats: '🗂 *{report}*\nОтметьте категории:\nВыбрано: {n}/{m}',
    no_cats_chosen: '⚠️ Выберите хотя бы одну категорию.',
    btn_back_spots: '◀️ К филиалам',
  },
};

function t(lang, key, params) {
  const dict = S[lang] || S.uz;
  let s = dict[key] !== undefined ? dict[key] : (S.uz[key] !== undefined ? S.uz[key] : key);
  if (params) {
    for (const k of Object.keys(params)) s = s.split(`{${k}}`).join(String(params[k]));
  }
  return s;
}

module.exports = { t, S };
